CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Documents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" character varying(255) NOT NULL,
    "DocumentType" character varying(50) NOT NULL,
    "UploadDate" timestamp with time zone NOT NULL,
    "ProcessedDate" timestamp with time zone NOT NULL,
    "StoragePath" character varying(255) NOT NULL,
    "IsProcessed" boolean NOT NULL,
    "ErrorMessage" character varying(500) NOT NULL,
    "UserEntityId" integer,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_Users_UserEntityId" FOREIGN KEY ("UserEntityId") REFERENCES "Users" ("Id")
);

CREATE TABLE "DocumentFields" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentId" integer NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Value" character varying(500) NOT NULL,
    "Confidence" real NOT NULL,
    CONSTRAINT "PK_DocumentFields" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentFields_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DocumentFields_DocumentId_Name" ON "DocumentFields" ("DocumentId", "Name");

CREATE INDEX "IX_Documents_DocumentType" ON "Documents" ("DocumentType");

CREATE INDEX "IX_Documents_FileName" ON "Documents" ("FileName");

CREATE INDEX "IX_Documents_UserEntityId" ON "Documents" ("UserEntityId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250331091523_InitialCreate', '8.0.14');

COMMIT;

